---
# tasks file for managed-clusters-role

- name: Set a clustername based on the host run against
  ansible.builtin.set_fact:
   clustername: "{{ inventory_hostname}}"

- name: Clear out previous runs
  ansible.builtin.file:
    path: ./cluster-manifests/
    state: absent

- name: Recreate manifests directory
  ansible.builtin.file:
    path: ./cluster-manifests/
    state: directory

- name: Create Namespace Object
  ansible.builtin.template:
    src: namespace.yaml.j2
    dest: ./cluster-manifests/{{ clustername }}-namespace
    mode: '0640'

- name: Create pull-secret Secret
  ansible.builtin.template:
    src: pull-secret.yaml.j2
    dest: ./cluster-manifests/{{ clustername }}-pull-secret
    mode: '0640'

- name: Create ssh key pair Secret
  ansible.builtin.template:
    src: ssh-key.yaml.j2
    dest: ./cluster-manifests/{{ clustername }}-ssh-key
    mode: '0640'

- name: Create managedcluster object
  ansible.builtin.template:
    src: managedcluster.yaml.j2
    dest: ./cluster-manifests/{{ clustername }}-managedcluster
    mode: '0640'

- name: Create klusterletaddonconfig object
  ansible.builtin.template:
    src: klusterletaddonconfig.yaml.j2
    dest: ./cluster-manifests/{{ clustername }}-klusterletaddonconfig
    mode: '0640'

- name: Create a temp file to house the install-config.yaml
  ansible.builtin.tempfile:
    state: file
    prefix: ""
  register: tempInstallConfig

- name: AWS Specific tasks
  block: 
  
    - name: Create install-config.yaml file
      ansible.builtin.template:
        src: aws-install-config.yaml.j2
        dest: "{{ tempInstallConfig.path }}"
        mode: '0600'

    - name: Create aws-creds Secret
      ansible.builtin.template:
        src: aws-creds.yaml.j2
        dest: ./cluster-manifests/{{ clustername }}-creds
        mode: '0640'

    - name: Create AWS clusterdeployment object
      ansible.builtin.template:
        src: aws-clusterdeployment.yaml.j2
        dest: ./cluster-manifests/{{ clustername }}-clusterdeployment
        mode: '0640'

    - name: Create AWS worker machinepool object
      ansible.builtin.template:
        src: aws-worker-machinepool.yaml.j2
        dest: ./cluster-manifests/{{ clustername }}-worker-machinepool
        mode: '0640'

    - name: Create AWS infra machinepool object
      ansible.builtin.template:
        src: aws-infra-machinepool.yaml.j2
        dest: ./cluster-manifests/{{ clustername }}-infra-machinepool
        mode: '0640'
      when: infra

  when: cloud_type == 'aws' 

# end AWS block

- name: vSphere specfic tasks
  block: 
  
    - name: Create install-config.yaml file
      ansible.builtin.template:
        src: vs-install-config.yaml.j2
        dest: "{{ tempInstallConfig.path }}"
        mode: '0600'

    - name: Create vs-creds Secret
      ansible.builtin.template:
        src: vs-creds.yaml.j2
        dest: ./cluster-manifests/{{ clustername }}-creds
        mode: '0640'

    - name: Create vs-certs Secret
      ansible.builtin.template:
        src: vs-certs.yaml.j2
        dest: ./cluster-manifests/{{ clustername }}-certs
        mode: '0640'

    - name: Create vSphere clusterdeployment object
      ansible.builtin.template:
        src: vs-clusterdeployment.yaml.j2
        dest: ./cluster-manifests/{{ clustername }}-clusterdeployment
        mode: '0640'

    - name: Create vSphere worker machinepool object
      ansible.builtin.template:
        src: vs-worker-machinepool.yaml.j2
        dest: ./cluster-manifests/{{ clustername }}-worker-machinepool
        mode: '0640'

    - name: Create vSphere infra machinepool object
      ansible.builtin.template:
        src: vs-infra-machinepool.yaml.j2
        dest: ./cluster-manifests/{{ clustername }}-infra-machinepool
        mode: '0640'
      when: infra

  when: cloud_type == 'vsphere' 

# end vSphere block

- name: Encode the install-config.yaml
  ansible.builtin.set_fact:
    encodedInstallConfig: "{{ lookup('ansible.builtin.file', tempInstallConfig.path) | b64encode }}"
  no_log: True

- name: Create install-config Secret
  ansible.builtin.template:
    src: cluster-install-config-secret.yaml.j2
    dest: ./cluster-manifests/{{ clustername }}-install-config
    mode: '0640'

- name: Generate full deployment
  ansible.builtin.template:
    src: full-deploy.j2
    dest: ./cluster-manifests/{{ clustername }}-full-deploy.yaml
    mode: '0640'
  vars:
    file_list:
      - ./cluster-manifests/{{ clustername }}-namespace
      - ./cluster-manifests/{{ clustername }}-clusterdeployment
      - ./cluster-manifests/{{ clustername }}-managedcluster
      - ./cluster-manifests/{{ clustername }}-worker-machinepool
      - ./cluster-manifests/{{ clustername }}-infra-machinepool
      - ./cluster-manifests/{{ clustername }}-pull-secret
      - ./cluster-manifests/{{ clustername }}-install-config
      - ./cluster-manifests/{{ clustername }}-ssh-key
      - ./cluster-manifests/{{ clustername }}-creds
      - ./cluster-manifests/{{ clustername }}-certs
      - ./cluster-manifests/{{ clustername }}-klusterletaddonconfig

- name: Clean up temp file
  ansible.builtin.file:
    path: "{{ tempInstallConfig.path }}"
    state: absent
  when: tempInstallConfig.path is defined
